name: Build and Run Odoo Containers

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'branch-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR ID as tag
        id: vars
        run: echo "tag=fb-pr-${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}

  run-containers:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker network
        run: docker network create -d bridge odoo_network
      
      - name: Run Postgres container
        run: |
          docker run -d \
            --network odoo_network \
            --name postgres \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres_admin \
            -e POSTGRES_DB=postgres \
            -p 5432:5432 \
            postgres:15

          echo "Waiting for Postgres to be ready..."
          sleep 10

      - name: List GHCR tags and run containers
        id: lsghcr
        env:
          GHCR_OWNER: my-org
          IMAGE_NAME: my-app
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOKEN=$GH_TOKEN
          IMAGE_PREFIX="ghcr.io/gldzzpro/odoo17"
          DEFAULT_PASS="odoo_pass"

          tags=$(curl -s -H "Authorization: Bearer $TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/user/packages/container/odoo17/versions" \
                | jq -r '.[].metadata.container.tags[]? | select(startswith("fb-"))')
          
          echo "tags=$tags" >> "$GITHUB_OUTPUT"

          for tag in $tags; do
            echo "tag: $tag"
            dbname="db_${tag//-/_}"
            dbuser="user_${tag//-/_}"
            dbpass="$DEFAULT_PASS"

            echo "Creating DB and user in Postgres for tag $tag..."

            # Create user if not exists
            docker exec -i postgres psql -U postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname = '$dbuser'" | grep -q 1 \
              || docker exec -i postgres psql -U postgres -c "CREATE ROLE $dbuser LOGIN PASSWORD '$dbpass';"

            # Create DB if not exists
            docker exec -i postgres psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '$dbname'" | grep -q 1 \
              || docker exec -i postgres psql -U postgres -c "CREATE DATABASE $dbname OWNER $dbuser;"

            # Grant privileges
            docker exec -i postgres psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $dbname TO $dbuser;"

            echo "Running Odoo container for tag $tag"

            docker run -d \
              --name "odoo_$tag" \
              --network odoo_network \
              -p 8069:8069 \
              -v ./custom_addons:/mnt/extra-addons:ro \
              -v odoo_$tag-data:/var/lib/odoo \
              "$IMAGE_PREFIX:$tag" \
              --db_host=postgres \
              --db_port=5432 \
              --db_user=$dbuser \
              --db_password=$dbpass \
              --database=$dbname \
              -i base,softifi_graph_module_dependency \
              --http-interface=0.0.0.0 \
              --proxy-mode

          done

          sleep 10
          docker ps

      - name: Get Docker instances
        id: docker_instances
        run: |
          echo "Tags are: ${{ steps.lsghcr.outputs.tags }}"

          tags="${{ steps.lsghcr.outputs.tags }}"
          DOCKER_INSTANCES=""
          for tag in $tags; do
            name="odoo_${tag}"
            url="http://${name}:8069"
            DOCKER_INSTANCES+="${name}:${url},"
          done

          # Remove trailing comma
          DOCKER_INSTANCES="${DOCKER_INSTANCES%,}"

          echo "Final DOCKER_INSTANCES: $DOCKER_INSTANCES"

          # Export for use in later steps
          echo "docker_instances=$DOCKER_INSTANCES" >> "$GITHUB_OUTPUT"

      - name: Run Graph-SYNC Project
        run: |
            docker_instances="${{ steps.docker_instances.outputs.docker_instances }}"
            echo "docker_instances: $docker_instances"
            docker run --network odoo_network \
              -e DOCKER_INSTANCES="$docker_instances" \
              ghcr.io/gldzzpro/graph_sync:latest
            

            sleep 10 

            docker ps

      - name: Run Neo4j Sync Project
        run: |
            echo "🔄 Starting Neo4j Sync container..."
            docker run -d \
              --name neo4j_sync \
              --network odoo_network \
              -p 8001:8001 \
              -e NEO4J_URI="neo4j+s://6e0e193c.databases.neo4j.io" \
              -e NEO4J_USERNAME="neo4j" \
              -e NEO4J_PASSWORD="5EFKS7g0FDIbNCSexts91WZJfkufYSKxw6FcJPoZOro" \
              -e LOG_LEVEL="DEBUG" \
              ghcr.io/gldzzpro/neo4j_sync:latest
            
            echo "Waiting for Neo4j Sync to be ready..."
            sleep 10
            
            echo "✅ Neo4j Sync container started"
            docker ps


          
