name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
      - 'branch-*'
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR ID as tag
        id: vars
        run: echo "tag=fb-pr-${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}

  list-ghcr-tags:
    runs-on: ubuntu-latest
    steps:
      - name: List GHCR tags for a container image

        env:
          GHCR_OWNER: my-org               # <- Change this
          IMAGE_NAME: my-app               # <- Change this
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              # GitHub token
              TOKEN=$GH_TOKEN
              IMAGE_PREFIX="ghcr.io/gldzzpro/odoo17"
              
              # Get all tags that start with fb-
              tags=$(curl -s -H "Authorization: Bearer $TOKEN" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/user/packages/container/odoo17/versions" \
                    | jq -r '.[].metadata.container.tags[]? | select(startswith("fb-"))')
              
              # Run a container for each tag
              for tag in $tags; do
                  echo "Running container for tag: $tag"
                  docker run -d --name "odoo_$tag" "$IMAGE_PREFIX:$tag"
              done

              sleep 10

              docker ps

              echo "edes edes"